tap "felixkratz/formulae"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "turbot/tap"
# Simple, modern, secure file encryption
brew "age"
# Asciicast to GIF converter
brew "agg"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Record and share terminal sessions
brew "asciinema"
# Highly capable, feature-rich programming language
brew "perl"
# Aquarium animation in ASCII art
brew "asciiquarium"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Garbage collector for C and C++
brew "bdw-gc"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Cross-platform make
brew "cmake"
# Validating, recursive, caching DNS resolver
brew "unbound"
# C library SSHv1/SSHv2 client and server protocols
brew "libssh"
# Emulator for x86 and PowerPC
brew "qemu"
# Linux virtual machines
brew "lima"
# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima"
# Load/unload environment variables based on $PWD
brew "direnv"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Docker CLI plugin for extended build capabilities with BuildKit
brew "docker-buildx"
# Isolated development environments using Docker
brew "docker-compose"
# Disk Usage/Free Utility - a better 'df' alternative
brew "duf"
# Classic UNIX line editor
brew "ed"
# Modern replacement for 'ls'
brew "exa"
# Audio codec
brew "opus"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# GitHub command-line tool
brew "gh"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Image processing tools collection
brew "graphicsmagick"
# GNU grep, egrep and fgrep
brew "grep"
# Improved top (interactive process viewer)
brew "htop"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Image loading and rendering library
brew "imlib2"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Convert pixel information into colored ASCII art
brew "libcaca"
# Postgres C API library
brew "libpq"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Utility for directing compilation
brew "make"
# Mac App Store command-line interface
brew "mas"
# Show markdown documents on text terminals
brew "mdcat"
# Fast and user friendly build system
brew "meson"
# Remote terminal application
brew "mosh"
# Video processing framework with simplicity in mind
brew "vapoursynth"
# Fork of youtube-dl with additional features and fixes
brew "yt-dlp"
# Media player based on MPlayer and mplayer2
brew "mpv"
# Open source relational database management system
brew "mysql-client"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Display the PID number for a given process name
brew "pidof"
# Manage compile and link flags for libraries
brew "pkg-config"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Show ps output as a tree
brew "pstree"
# Python interface to Tcl/Tk
brew "python-tk@3.11"
# File browser
brew "ranger"
# Unofficial Bitwarden CLI client
brew "rbw"
# Rust toolchain installer
brew "rustup-init"
# SOcket CAT: netcat on steroids
brew "socat"
# Use SQL to instantly query your cloud services
brew "steampipe"
# Tail multiple Kubernetes pods & their containers
brew "stern"
# Tool to generate documentation from Terraform modules
brew "terraform-docs"
# Text interface for Git repositories
brew "tig"
# Terminal image and video viewer
brew "timg"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# High-performance HTTP accelerator
brew "varnish"
# Pager/text based browser
brew "w3m"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Tracks most-used directories to make cd smarter
brew "z"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# Boundary
brew "hashicorp/tap/boundary"
# Vlt CLI
brew "hashicorp/tap/vlt"
# Simple hotkey-daemon for macOS.
brew "koekeishiya/formulae/skhd"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
# Free and open-source web browser
cask "chromium"
# Reimagine your terminal
cask "fig"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# CLI graphics framework
cask "kui"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
